api:
  fileUploadPath: C:\upload\hn
  salt: Gobest_zghn_As
  apiWebSite:  http://39.108.88.223:8087/hn-api
  reviewBaseUrl: ${api.apiWebSite}/show-page/show-article/
  courseUrl: ${api.apiWebSite}/show-page/course/
  h5Parameter: ?token={0}&deviceId={1}
  openSign: false
  apkDownload: http://ghypt.hnszgh.org:9082/hngh-0927.apk
  appStoreLink: https://itunes.apple.com/cn/app/id1436667548?mt=8
  upperIntegral: 10
  matrixLogo: matrix_log.png
  phpSite: http://we.gobestsoft.com/hnapp/
  mobileMostTime: 20
  downloadUrl: ${api.apiWebSite}/show-page/download
  writeLogs: false

uploadSite:
  address: http://39.108.88.223:8087/hn-upload/ #图片资源路径

server:
  port: 10002
  contextPath: /hn-api

mybatis-plus:
  mapper-locations: classpath*:com/gobestsoft/common/**/mapping/*.xml
  typeAliasesPackage: com.gobestsoft.common.modular.*.model
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true #mybatis lazy loading
    multipleResultSetsEnabled: true
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #open for debug

spring:
  jmx:
    default-domain: hn-api
  datasource:
    url : jdbc:mysql://39.108.88.223:12306/hngh_test?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&characterEncoding=utf8
    username : admin
    password : gobest_123$%^&

  aop:
    proxy-target-class: true
  http:
      multipart.maxFileSize: 100Mb #max file size of upload
      multipart.maxRequestSize: 100Mb #max file size of request
  redis:
      database: 0 # Redis database
      host: 127.0.0.1 # Redis host
      port: 6379  # Redis port
      password: #Redis password
      pool.max-active: 8
      pool.max-wait: -1
      timeout: 0
  resources:
     static-locations: classpath:/static/
     chain:
       cache: false
  rabbitmq:
    host: 118.31.4.49
    port: 5672
    username: guest
    password: guest
  thymeleaf:
      mode: LEGACYHTML5
      encoding: UTF-8
      cache: false
      check-template-location: true
      enabled: true
      prefix: classpath:/templates/
logging:
  level.root: info
  level.com.gobestsoft: debug
  path: /Users/shenweitao/jianlang/log/ #Save path of log
  file: hn-api #File name of save log
jpush:
  masterSecret: 1
  appKey: 1