package com.gobestsoft.common.modular.dao.model;

import java.io.Serializable;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName("app_sms_log")
public class AppSmsLogPojo extends Model<AppSmsLogPojo> {

    private static final long serialVersionUID = 1L;

	@Override
	protected Serializable pkVal() {
		return this.id;
	}
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.push_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer pushId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.uid
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.mobile
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.title
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.content
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.is_open
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.push_from
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String pushFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.push_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer pushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.status
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.result
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.create_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.update_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sms_log.del_flg
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.id
     *
     * @return the value of app_sms_log.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.id
     *
     * @param id the value for app_sms_log.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.push_id
     *
     * @return the value of app_sms_log.push_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.push_id
     *
     * @param pushId the value for app_sms_log.push_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setPushId(Integer pushId) {
        this.pushId = pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.uid
     *
     * @return the value of app_sms_log.uid
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.uid
     *
     * @param uid the value for app_sms_log.uid
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.mobile
     *
     * @return the value of app_sms_log.mobile
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.mobile
     *
     * @param mobile the value for app_sms_log.mobile
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.title
     *
     * @return the value of app_sms_log.title
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.title
     *
     * @param title the value for app_sms_log.title
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.content
     *
     * @return the value of app_sms_log.content
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.content
     *
     * @param content the value for app_sms_log.content
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.is_open
     *
     * @return the value of app_sms_log.is_open
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.is_open
     *
     * @param isOpen the value for app_sms_log.is_open
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setIsOpen(Short isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.push_from
     *
     * @return the value of app_sms_log.push_from
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getPushFrom() {
        return pushFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.push_from
     *
     * @param pushFrom the value for app_sms_log.push_from
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setPushFrom(String pushFrom) {
        this.pushFrom = pushFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.push_type
     *
     * @return the value of app_sms_log.push_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.push_type
     *
     * @param pushType the value for app_sms_log.push_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.status
     *
     * @return the value of app_sms_log.status
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.status
     *
     * @param status the value for app_sms_log.status
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.result
     *
     * @return the value of app_sms_log.result
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.result
     *
     * @param result the value for app_sms_log.result
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.create_time
     *
     * @return the value of app_sms_log.create_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.create_time
     *
     * @param createTime the value for app_sms_log.create_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.update_time
     *
     * @return the value of app_sms_log.update_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.update_time
     *
     * @param updateTime the value for app_sms_log.update_time
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sms_log.del_flg
     *
     * @return the value of app_sms_log.del_flg
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sms_log.del_flg
     *
     * @param delFlg the value for app_sms_log.del_flg
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setDelFlg(Short delFlg) {
        this.delFlg = delFlg;
    }
}