package com.gobestsoft.common.modular.dao.model;

import java.io.Serializable;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName("org_contract")
public class OrgContractPojo extends Model<OrgContractPojo> {

    private static final long serialVersionUID = 1L;

	@Override
	protected Serializable pkVal() {
		return this.deptId;
	}
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_contract.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_contract.contract_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_contract.init_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String initDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_contract.createtime
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_contract.is_group_constract
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short isGroupConstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_contract.dept_id
     *
     * @return the value of org_contract.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_contract.dept_id
     *
     * @param deptId the value for org_contract.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_contract.contract_id
     *
     * @return the value of org_contract.contract_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_contract.contract_id
     *
     * @param contractId the value for org_contract.contract_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_contract.init_date
     *
     * @return the value of org_contract.init_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getInitDate() {
        return initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_contract.init_date
     *
     * @param initDate the value for org_contract.init_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setInitDate(String initDate) {
        this.initDate = initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_contract.createtime
     *
     * @return the value of org_contract.createtime
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_contract.createtime
     *
     * @param createtime the value for org_contract.createtime
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_contract.is_group_constract
     *
     * @return the value of org_contract.is_group_constract
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getIsGroupConstract() {
        return isGroupConstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_contract.is_group_constract
     *
     * @param isGroupConstract the value for org_contract.is_group_constract
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setIsGroupConstract(Short isGroupConstract) {
        this.isGroupConstract = isGroupConstract;
    }
}