package com.gobestsoft.common.modular.dao.model;

import java.io.Serializable;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName("org_dept_ext")
public class OrgDeptExtPojo extends Model<OrgDeptExtPojo> {

    private static final long serialVersionUID = 1L;

	@Override
	protected Serializable pkVal() {
		return this.deptId;
	}
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.dept_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short deptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.org_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.economy_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String economyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.district_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.street_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String streetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.unit_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short unitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.industry_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short industryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.unit_name
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.base_org_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short baseOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.change_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String changeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.telephone
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.employee_cnt
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private String employeeCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept_ext.is_closed
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Short isClosed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.dept_id
     *
     * @return the value of org_dept_ext.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.dept_id
     *
     * @param deptId the value for org_dept_ext.dept_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.dept_type
     *
     * @return the value of org_dept_ext.dept_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.dept_type
     *
     * @param deptType the value for org_dept_ext.dept_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setDeptType(Short deptType) {
        this.deptType = deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.org_code
     *
     * @return the value of org_dept_ext.org_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.org_code
     *
     * @param orgCode the value for org_dept_ext.org_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.economy_type
     *
     * @return the value of org_dept_ext.economy_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getEconomyType() {
        return economyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.economy_type
     *
     * @param economyType the value for org_dept_ext.economy_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setEconomyType(String economyType) {
        this.economyType = economyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.district_code
     *
     * @return the value of org_dept_ext.district_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.district_code
     *
     * @param districtCode the value for org_dept_ext.district_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.street_code
     *
     * @return the value of org_dept_ext.street_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getStreetCode() {
        return streetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.street_code
     *
     * @param streetCode the value for org_dept_ext.street_code
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setStreetCode(String streetCode) {
        this.streetCode = streetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.unit_type
     *
     * @return the value of org_dept_ext.unit_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.unit_type
     *
     * @param unitType the value for org_dept_ext.unit_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setUnitType(Short unitType) {
        this.unitType = unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.industry_type
     *
     * @return the value of org_dept_ext.industry_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.industry_type
     *
     * @param industryType the value for org_dept_ext.industry_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setIndustryType(Short industryType) {
        this.industryType = industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.unit_name
     *
     * @return the value of org_dept_ext.unit_name
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.unit_name
     *
     * @param unitName the value for org_dept_ext.unit_name
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.base_org_type
     *
     * @return the value of org_dept_ext.base_org_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getBaseOrgType() {
        return baseOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.base_org_type
     *
     * @param baseOrgType the value for org_dept_ext.base_org_type
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setBaseOrgType(Short baseOrgType) {
        this.baseOrgType = baseOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.change_date
     *
     * @return the value of org_dept_ext.change_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.change_date
     *
     * @param changeDate the value for org_dept_ext.change_date
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setChangeDate(String changeDate) {
        this.changeDate = changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.telephone
     *
     * @return the value of org_dept_ext.telephone
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.telephone
     *
     * @param telephone the value for org_dept_ext.telephone
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.employee_cnt
     *
     * @return the value of org_dept_ext.employee_cnt
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public String getEmployeeCnt() {
        return employeeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.employee_cnt
     *
     * @param employeeCnt the value for org_dept_ext.employee_cnt
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setEmployeeCnt(String employeeCnt) {
        this.employeeCnt = employeeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept_ext.is_closed
     *
     * @return the value of org_dept_ext.is_closed
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Short getIsClosed() {
        return isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept_ext.is_closed
     *
     * @param isClosed the value for org_dept_ext.is_closed
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setIsClosed(Short isClosed) {
        this.isClosed = isClosed;
    }
}