package com.gobestsoft.common.modular.dao.model;

import java.io.Serializable;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName("r_article_category")
public class RArticleCategoryPojo extends Model<RArticleCategoryPojo> {

    private static final long serialVersionUID = 1L;

	@Override
	protected Serializable pkVal() {
		return this.id;
	}
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_article_category.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_article_category.article_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_article_category.category_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_article_category.id
     *
     * @return the value of r_article_category.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_article_category.id
     *
     * @param id the value for r_article_category.id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_article_category.article_id
     *
     * @return the value of r_article_category.article_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_article_category.article_id
     *
     * @param articleId the value for r_article_category.article_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_article_category.category_id
     *
     * @return the value of r_article_category.category_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_article_category.category_id
     *
     * @param categoryId the value for r_article_category.category_id
     *
     * @mbg.generated Tue Dec 05 12:46:32 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}